"""empty message

Revision ID: 0a564e642c8c
Revises: dcf0ccce1b70
Create Date: 2020-10-18 16:32:08.190000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a564e642c8c'
down_revision = 'dcf0ccce1b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'artist_genre_artist_id_fkey', 'artist_genre', type_='foreignkey')
    op.create_foreign_key(None, 'artist_genre', 'artist', ['artist_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'show_venue_id_fkey', 'show', type_='foreignkey')
    op.drop_constraint(u'show_artist_id_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'artist', ['artist_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'show', 'venue', ['venue_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'venue_genre_venue_id_fkey', 'venue_genre', type_='foreignkey')
    op.create_foreign_key(None, 'venue_genre', 'venue', ['venue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue_genre', type_='foreignkey')
    op.create_foreign_key(u'venue_genre_venue_id_fkey', 'venue_genre', 'venue', ['venue_id'], ['id'])
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key(u'show_artist_id_fkey', 'show', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key(u'show_venue_id_fkey', 'show', 'venue', ['venue_id'], ['id'])
    op.drop_constraint(None, 'artist_genre', type_='foreignkey')
    op.create_foreign_key(u'artist_genre_artist_id_fkey', 'artist_genre', 'artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###
