"""empty message

Revision ID: 346d6cb26ce8
Revises: 0a564e642c8c
Create Date: 2020-10-20 00:31:43.980000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346d6cb26ce8'
down_revision = '0a564e642c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'show_pkey', 'show', type_='primary')
    op.create_primary_key('show_primary_key', 'show', ['artist_id', 'venue_id', 'start_time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'show_pkey', 'show', type_='primary')
    op.create_primary_key('show_primary_key', 'show', ['artist_id', 'venue_id'])
    # ### end Alembic commands ###
