"""empty message

Revision ID: 54382fde2e63
Revises: cbfa51f7f809
Create Date: 2020-10-17 16:21:02.082000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54382fde2e63'
down_revision = 'cbfa51f7f809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE show DROP CONSTRAINT "show_venue_id_fkey"')
    op.execute('ALTER TABLE venue_genre DROP CONSTRAINT "venue_genre_venue_id_fkey"')

    op.execute('ALTER TABLE show ALTER COLUMN venue_id SET DATA TYPE CHAR(120)')
    op.execute('ALTER TABLE venue_genre ALTER COLUMN venue_id SET DATA TYPE CHAR(120)')
    op.execute('ALTER TABLE venue ALTER COLUMN id SET DATA TYPE CHAR(120)')

    op.execute('ALTER TABLE show ADD FOREIGN KEY (venue_id) REFERENCES venue(id)')
    op.execute('ALTER TABLE venue_genre ADD FOREIGN KEY (venue_id) REFERENCES venue(id)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE show DROP CONSTRAINT "show_venue_id_fkey"')
    op.execute('ALTER TABLE venue_genre DROP CONSTRAINT "venue_genre_venue_id_fkey"')

    op.execute('ALTER TABLE show ALTER COLUMN venue_id SET DATA TYPE INTEGER USING venue_id::integer')
    op.execute('ALTER TABLE venue_genre ALTER COLUMN venue_id SET DATA TYPE INTEGER USING venue_id::integer')
    op.execute('ALTER TABLE venue ALTER COLUMN id SET DATA TYPE INTEGER USING id::integer')

    op.execute('ALTER TABLE show ADD FOREIGN KEY (venue_id) REFERENCES venue(id)')
    op.execute('ALTER TABLE venue_genre ADD FOREIGN KEY (venue_id) REFERENCES venue(id)')
    # ### end Alembic commands ###
