"""empty message

Revision ID: 5ffed2a69e05
Revises: 54382fde2e63
Create Date: 2020-10-17 23:45:58.811000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffed2a69e05'
down_revision = '54382fde2e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'show_artist_id_fkey', 'show', type_='foreignkey')
    op.drop_constraint(u'artist_genre_venue_id_fkey', 'artist_genre', type_='foreignkey')
    op.drop_constraint(u'artist_genre_pkey', 'artist_genre', type_='primary')
    op.add_column('artist_genre', sa.Column('artist_id', sa.String(120), primary_key=True, nullable=False))
    op.create_primary_key('artist_genre_primary_key', 'artist_genre', ['artist_id', 'genre'])
    op.drop_column('artist_genre', 'venue_id')


    op.drop_column('show', 'artist_id')
    op.add_column('show', sa.Column('artist_id', sa.String(120), primary_key=True, nullable=False))
    op.create_primary_key('show_artist_primary_key', 'show', ['artist_id', 'venue_id'])
    op.drop_column('artist', 'id')
    op.add_column('artist', sa.Column('id', sa.String(120), primary_key=True, nullable=False))
    op.create_primary_key('artist_primary_key', 'artist', ['id'])

    op.create_foreign_key(None, 'show', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'artist_genre', 'artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_genre', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'artist_genre', type_='foreignkey')
    op.create_foreign_key(u'artist_genre_venue_id_fkey', 'artist_genre', 'artist', ['venue_id'], ['id'])
    op.drop_column('artist_genre', 'artist_id')

    op.drop_constraint(u'show_artist_id_fkey', 'show', type_='foreignkey')
    op.drop_constraint(u'artist_genre_artist_id_fkey', 'artist_genre', type_='foreignkey')

    op.drop_column('show', 'artist_id')
    op.add_column('show', sa.Column('artist_id'. sa.Integer, nullable=False))
    op.add_column('artist', sa.Column('id'. sa.Integer, nullable=False))

    op.create_foreign_key(u'show_artist_id_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(u'artist_genre_artist_id_fkey', 'artist_genre', type_='foreignkey')
    # ### end Alembic commands ###
