"""empty message

Revision ID: 7993b6bb5373
Revises: a2ec8828e1f6
Create Date: 2020-10-18 15:52:29.500000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7993b6bb5373'
down_revision = 'a2ec8828e1f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'crust')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('crust', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
