"""empty message

Revision ID: ab7398f2a482
Revises: 5ffed2a69e05
Create Date: 2020-10-18 08:54:49.032000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab7398f2a482'
down_revision = '5ffed2a69e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_genre')
    op.drop_table('artist_genre')
    op.drop_table('show')
    op.drop_table('genre')
    op.drop_table('venue')
    op.drop_table('artist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('seeking_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'artist_primary_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('venue',
    sa.Column('id', sa.CHAR(length=120), server_default=sa.text(u"nextval('venue_id_seq'::regclass)"), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('seeking_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('crust', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'venue_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('genre',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u"nextval('genre_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'genre_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('show',
    sa.Column('venue_id', sa.CHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], [u'artist.id'], name=u'show_artist_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], [u'venue.id'], name=u'show_venue_id_fkey'),
    sa.PrimaryKeyConstraint('artist_id', 'venue_id', name=u'show_artist_primary_key')
    )
    op.create_table('artist_genre',
    sa.Column('genre', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], [u'artist.id'], name=u'artist_genre_artist_id_fkey'),
    sa.ForeignKeyConstraint(['genre'], [u'genre.id'], name=u'artist_genre_genre_fkey'),
    sa.PrimaryKeyConstraint('artist_id', 'genre', name=u'artist_genre_primary_key')
    )
    op.create_table('venue_genre',
    sa.Column('venue_id', sa.CHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('genre', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genre'], [u'genre.id'], name=u'venue_genre_genre_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], [u'venue.id'], name=u'venue_genre_venue_id_fkey'),
    sa.PrimaryKeyConstraint('venue_id', 'genre', name=u'venue_genre_pkey')
    )
    # ### end Alembic commands ###
