"""empty message

Revision ID: cbfa51f7f809
Revises: 60c3e9c3cc54
Create Date: 2020-10-16 05:38:48.968720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbfa51f7f809'
down_revision = '60c3e9c3cc54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_genre',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'genre')
    )
    op.create_table('venue_genre',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'genre')
    )
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_table('venue_genre')
    op.drop_table('artist_genre')
    op.drop_table('genre')
    # ### end Alembic commands ###
